return {
	require("ifavilanvim.plugins.colorschemes"),
	-- require("ifavilanvim.plugins.cmp"),
	require("ifavilanvim.plugins.blink"),
	require("ifavilanvim.plugins.telescope"),
	require("ifavilanvim.plugins.treesitter"),
	require("ifavilanvim.plugins.autopairs"),
	require("ifavilanvim.plugins.mason"),
	require("ifavilanvim.plugins.lspconfig"),
	require("ifavilanvim.plugins.lsp-zero"),
	require("ifavilanvim.plugins.todo-comments"),
	require("ifavilanvim.plugins.trouble"),
	require("ifavilanvim.plugins.gitsigns"),
	require("ifavilanvim.plugins.guess-indent"),
	require("ifavilanvim.plugins.dadbod"),
	require("ifavilanvim.plugins.mini-files"),
	require("ifavilanvim.plugins.mini-cursorword"),
	require("ifavilanvim.plugins.obsidian"),
	require("ifavilanvim.plugins.showkeys"),
	require("ifavilanvim.plugins.leetcode"),
	require("ifavilanvim.plugins.vim-surround"),
	require("ifavilanvim.plugins.lualine"),
	require("ifavilanvim.plugins.nvim-jdtls"),
	require("ifavilanvim.plugins.git-conflict"),

	-- require("ifavilanvim.plugins.copilot"),
	-- require("ifavilanvim.plugins.markview"),
	-- require("ifavilanvim.plugins.nvim-metals")
	-- require("ifavilanvim.plugins.modicator"),
	-- require("ifavilanvim.plugins.lightline"),

	require("ifavilanvim.custom_plugins.term-window"),
}
